### PR TITLE
transition to monorepo and add webpack loader

### PR DESCRIPTION
**Pull request by eankeen**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
adds a webpack loader

draft because the loader doesn't actually work yet and some files still need to be reorganized (like linter files), and another thing

### CODE REVIEW

**Comment by jbis9051** [comment]
Also what's with this workspaces stuffs

**Comment by eankeen** [comment]
@jbis9051 wdym by "workspace stuffs"

and yeah things will be changed to yarn before this is merged

**Comment by jbis9051** [comment]
Nah we using npm

**Comment by jbis9051** [comment]
We can discuss yarn workspaces in slack, ping me

**Pull request merged**
