### PR TITLE
added fayd as 'as'

### PR DESCRIPTION
**Pull request by faisalsayed10**

### CODE REVIEW

**Comment by aditya1rawat** [comment]
@faisalsayed10 could you let me know which keyword you would prefer? You have requested 1 here, and two other ones on airtable which are for "int" and "super".

Thanks!

**Comment by faisalsayed10** [comment]
@aditya1rawat  umm... int was a type so @Matt-Gleich said, we can't use that. I wud go for 'as' :)

**Comment by Matt-Gleich** [comment]
Yep `as` should work!

**Comment by aditya1rawat** [comment]
Alright cool. Thanks Matt!

**Pull request merged**
