### PR TITLE
Add semicolon

### PR DESCRIPTION
**Pull request by benaubin**

### CODE REVIEW

**Comment by aditya1rawat** [comment]
RIP

**Comment by benaubin** [comment]
@jbis9051  Ha okay - I saw someone had `=`, so I thought this would be fun. 😄 Could I get `finally` then?

**Comment by aditya1rawat** [comment]
yessir

**Comment by aditya1rawat** [comment]
i named your keyword as ben. is that fine? i can change it to benaubin if you want to

**Comment by benaubin** [comment]
> i named your keyword as ben. is that fine? i can change it to benaubin if you want to.

`ben` is perfect! Tysm

**Pull request closed without merging**
