### PR TITLE
added int keyword

### PR DESCRIPTION
**Pull request by faisalsayed10**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by Matt-Gleich** [comment]
Hey @faisalsayed10! `int` is a type, not a keyword. Is there some keyword or conditional operator you would like instead?

**Comment by faisalsayed10** [comment]
i think the OPENKEYWORDS.md is outdated, can u please update it and also can you suggest me what should i keep?
maybe a '+' operator?

**Comment by Matt-Gleich** [comment]
`+` is also not a conditional operator. Conditional operators consist of comparison and logical operators https://www.w3schools.com/Js/js_operators.asp

**Comment by faisalsayed10** [comment]
what about && ?

**Comment by faisalsayed10** [comment]
or else the 'as' keyword. when we use import __ 'as' ___

**Comment by faisalsayed10** [comment]
check out my new PR, i'm closing this

**Pull request closed without merging**
